apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          volumeMounts:
            - mountPath: /etc/telegraf
              name: telegraf-config
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  selector:
    app: telegraf
  ports:
    - name: telegraf-udp # Portname für den ersten Port
      port: 8125
      targetPort: 8125
      protocol: UDP # Beispielprotokoll, falls UDP benötigt wird
    - name: telegraf-tcp # Portname für den zweiten Port
      port: 8092
      targetPort: 8092
      protocol: TCP # Beispielprotokoll für TCP
  type: ClusterIP
