apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: monitoring
data:
  telegraf.conf: |
    # Telegraf Configuration

    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "telegraf"
      username = "admin"
      password = "your-password"

    [[inputs.kubernetes]]
      url = "https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
      bearer_token = "/var/run/secrets/kubernetes.io/serviceaccount/token"
      fieldinclude = ["cpu_usage", "memory_usage", "network", "disk"]

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false

    [[inputs.mem]]
      #mem = true
      #swap = true

    [[inputs.disk]]
      mount_points = ["/", "/mnt"]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

    [[inputs.net]]
      interfaces = ["eth0", "lo"]

    [[inputs.system]]
      ## CPU Temp on Linux will use the value in /sys/class/thermal/thermal_zone0/temp
      ## The value is in millidegrees Celsius, so divide by 1000 to get Celsius.
      fieldpass = ["temperature"]
