apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
        - name: telegraf
          image: telegraf:latest
          volumeMounts:
            - mountPath: /etc/telegraf
              name: telegraf-config
      volumes:
        - name: telegraf-config
          configMap:
            name: telegraf-config
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  selector:
    app: telegraf
  ports:
    - port: 8125
      targetPort: 8125
    - port: 8092
      targetPort: 8092
  type: ClusterIP
