apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    # Telegraf Configuration
    [[outputs.influxdb]]
      urls = ["http://influxdb:8086"]
      database = "telegraf"
      username = "admin"
      password = "your-password"

    [[inputs.cpu]]
      percpu = true
      totalcpu = true
      collect_cpu_time = false

    [[inputs.mem]]
      mem = true
      swap = true

    [[inputs.disk]]
      mount_points = ["/", "/mnt"]
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

    [[inputs.net]]
      interfaces = ["eth0", "lo"]
